/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ExceptionService } from "../exception.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExceptionCreateInput } from "./ExceptionCreateInput";
import { Exception } from "./Exception";
import { ExceptionFindManyArgs } from "./ExceptionFindManyArgs";
import { ExceptionWhereUniqueInput } from "./ExceptionWhereUniqueInput";
import { ExceptionUpdateInput } from "./ExceptionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ExceptionControllerBase {
  constructor(
    protected readonly service: ExceptionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Exception })
  @nestAccessControl.UseRoles({
    resource: "Exception",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createException(
    @common.Body() data: ExceptionCreateInput
  ): Promise<Exception> {
    return await this.service.createException({
      data: {
        ...data,

        asset: data.asset
          ? {
              connect: data.asset,
            }
          : undefined,
      },
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        created: true,
        exceptionEnd: true,
        exceptionReason: true,
        exceptionStart: true,
        exceptionType: true,
        id: true,
        updated: true,
        updatedBy: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Exception] })
  @ApiNestedQuery(ExceptionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Exception",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async exceptions(@common.Req() request: Request): Promise<Exception[]> {
    const args = plainToClass(ExceptionFindManyArgs, request.query);
    return this.service.exceptions({
      ...args,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        created: true,
        exceptionEnd: true,
        exceptionReason: true,
        exceptionStart: true,
        exceptionType: true,
        id: true,
        updated: true,
        updatedBy: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Exception })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Exception",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async exception(
    @common.Param() params: ExceptionWhereUniqueInput
  ): Promise<Exception | null> {
    const result = await this.service.exception({
      where: params,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        created: true,
        exceptionEnd: true,
        exceptionReason: true,
        exceptionStart: true,
        exceptionType: true,
        id: true,
        updated: true,
        updatedBy: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Exception })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Exception",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateException(
    @common.Param() params: ExceptionWhereUniqueInput,
    @common.Body() data: ExceptionUpdateInput
  ): Promise<Exception | null> {
    try {
      return await this.service.updateException({
        where: params,
        data: {
          ...data,

          asset: data.asset
            ? {
                connect: data.asset,
              }
            : undefined,
        },
        select: {
          asset: {
            select: {
              id: true,
            },
          },

          created: true,
          exceptionEnd: true,
          exceptionReason: true,
          exceptionStart: true,
          exceptionType: true,
          id: true,
          updated: true,
          updatedBy: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Exception })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Exception",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteException(
    @common.Param() params: ExceptionWhereUniqueInput
  ): Promise<Exception | null> {
    try {
      return await this.service.deleteException({
        where: params,
        select: {
          asset: {
            select: {
              id: true,
            },
          },

          created: true,
          exceptionEnd: true,
          exceptionReason: true,
          exceptionStart: true,
          exceptionType: true,
          id: true,
          updated: true,
          updatedBy: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
